import type { Lang } from "./i18n"
import { translations } from "./i18n"

export type NodeStatus = "done" | "in-progress" | "todo" | "pending"

export interface RoadmapNode {
  id: string
  labelKey: keyof (typeof translations)["en"]
  x: number
  y: number
  width: number
  height: number
  status: NodeStatus
  detailKey: string
  color?: string
}

export interface RoadmapEdge {
  from: string
  to: string
}

export interface RoadmapData {
  id: string
  titleKey: keyof (typeof translations)["en"]
  descKey: keyof (typeof translations)["en"]
  nodes: RoadmapNode[]
  edges: RoadmapEdge[]
}

// Cores baseadas no estilo neon/dark mode
const COLOR_DONE = "#eeff00" // Amarelo Neon
const COLOR_IN_PROGRESS = "#00ff88" // Verde Neon
const COLOR_TODO = "#ffffff" // Branco
const COLOR_PENDING = "#475569" // Slate 600 (Cinza escuro para itens futuros)

export const roadmaps: RoadmapData[] = [
  {
    id: "sap-mm",
    titleKey: "cardSapMM",
    descKey: "descSapMM",
    nodes: [
      {
        id: "mm1",
        labelKey: "nodeMM1",
        x: 300,
        y: 60,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "mmOrgStructure",
        color: COLOR_DONE,
      },
      {
        id: "mm2",
        labelKey: "nodeMM2",
        x: 80,
        y: 170,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "mmMasterData",
        color: COLOR_DONE,
      },
      {
        id: "mm3",
        labelKey: "nodeMM3",
        x: 520,
        y: 170,
        width: 240,
        height: 52,
        status: "in-progress",
        detailKey: "mmPurchasingMaster",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "mm4",
        labelKey: "nodeMM4",
        x: 300,
        y: 280,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "mmPurchaseReq",
        color: COLOR_TODO,
      },
      {
        id: "mm5",
        labelKey: "nodeMM5",
        x: 80,
        y: 390,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "mmPurchaseOrder",
        color: COLOR_TODO,
      },
      {
        id: "mm6",
        labelKey: "nodeMM6",
        x: 520,
        y: 390,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "mmReleaseStrategy",
        color: COLOR_PENDING,
      },
      {
        id: "mm7",
        labelKey: "nodeMM7",
        x: 300,
        y: 500,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "mmInventoryMigo",
        color: COLOR_PENDING,
      },
      {
        id: "mm8",
        labelKey: "nodeMM8",
        x: 80,
        y: 610,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "mmInvoiceMiro",
        color: COLOR_PENDING,
      },
      {
        id: "mm9",
        labelKey: "nodeMM9",
        x: 520,
        y: 610,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "mmOutlineAgreements",
        color: COLOR_PENDING,
      },
      {
        id: "mm10",
        labelKey: "nodeMM10",
        x: 300,
        y: 720,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "mmSubcontractingConsignment",
        color: COLOR_PENDING,
      },
      {
        id: "mm11",
        labelKey: "nodeMM11",
        x: 80,
        y: 830,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "mmMrp",
        color: COLOR_PENDING,
      },
      {
        id: "mm12",
        labelKey: "nodeMM12",
        x: 520,
        y: 830,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "mmDataAutomation",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "mm1", to: "mm2" },
      { from: "mm2", to: "mm3" },
      { from: "mm3", to: "mm4" },
      { from: "mm4", to: "mm5" },
      { from: "mm4", to: "mm6" },
      { from: "mm5", to: "mm7" },
      { from: "mm6", to: "mm7" },
      { from: "mm7", to: "mm8" },
      { from: "mm8", to: "mm9" },
      { from: "mm9", to: "mm10" },
      { from: "mm10", to: "mm11" },
      { from: "mm11", to: "mm12" },
    ],
  },
  {
    id: "power-apps",
    titleKey: "cardPowerApps",
    descKey: "descPowerApps",
    nodes: [
      {
        id: "pa1",
        labelKey: "nodePA1",
        x: 300,
        y: 60,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "canvas",
        color: COLOR_DONE,
      },
      {
        id: "pa2",
        labelKey: "nodePA2",
        x: 300,
        y: 160,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "canvas",
        color: COLOR_DONE,
      },
      {
        id: "pa3",
        labelKey: "nodePA3",
        x: 80,
        y: 260,
        width: 240,
        height: 52,
        status: "in-progress",
        detailKey: "canvas",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "pa4",
        labelKey: "nodePA4",
        x: 520,
        y: 260,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "canvas",
        color: COLOR_TODO,
      },
      {
        id: "pa5",
        labelKey: "nodePA5",
        x: 300,
        y: 360,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "canvas",
        color: COLOR_TODO,
      },
      {
        id: "pa6",
        labelKey: "nodePA6",
        x: 80,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "canvas",
        color: COLOR_PENDING,
      },
      {
        id: "pa7",
        labelKey: "nodePA7",
        x: 300,
        y: 560,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "canvas",
        color: COLOR_PENDING,
      },
      {
        id: "pa8",
        labelKey: "nodePA8",
        x: 300,
        y: 660,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "canvas",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "pa1", to: "pa2" },
      { from: "pa2", to: "pa3" },
      { from: "pa2", to: "pa4" },
      { from: "pa2", to: "pa5" },
      { from: "pa5", to: "pa6" },
      { from: "pa5", to: "pa7" },
      { from: "pa6", to: "pa8" },
      { from: "pa7", to: "pa8" },
    ],
  },
  {
    id: "demand-mgmt",
    titleKey: "cardDemand",
    descKey: "descDemand",
    nodes: [
      {
        id: "dm1",
        labelKey: "nodeDM1",
        x: 300,
        y: 60,
        width: 260,
        height: 52,
        status: "done",
        detailKey: "schema",
        color: COLOR_DONE,
      },
      {
        id: "dm2",
        labelKey: "nodeDM2",
        x: 300,
        y: 160,
        width: 260,
        height: 52,
        status: "in-progress",
        detailKey: "schema",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "dm3",
        labelKey: "nodeDM3",
        x: 300,
        y: 260,
        width: 260,
        height: 52,
        status: "todo",
        detailKey: "schema",
        color: COLOR_TODO,
      },
      {
        id: "dm4",
        labelKey: "nodeDM4",
        x: 300,
        y: 360,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "schema",
        color: COLOR_PENDING,
      },
      {
        id: "dm5",
        labelKey: "nodeDM5",
        x: 300,
        y: 460,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "schema",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "dm1", to: "dm2" },
      { from: "dm2", to: "dm3" },
      { from: "dm3", to: "dm4" },
      { from: "dm4", to: "dm5" },
    ],
  },
  // SAP SD Key User
  {
    id: "sap-sd",
    titleKey: "cardSapSD",
    descKey: "descSapSD",
    nodes: [
      {
        id: "sd1",
        labelKey: "nodeSD1",
        x: 300,
        y: 60,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "introSD",
        color: COLOR_DONE,
      },
      {
        id: "sd2",
        labelKey: "nodeSD2",
        x: 300,
        y: 160,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "introSD",
        color: COLOR_DONE,
      },
      {
        id: "sd3",
        labelKey: "nodeSD3",
        x: 80,
        y: 260,
        width: 240,
        height: 52,
        status: "in-progress",
        detailKey: "sales",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "sd4",
        labelKey: "nodeSD4",
        x: 520,
        y: 260,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "pricing",
        color: COLOR_TODO,
      },
      {
        id: "sd5",
        labelKey: "nodeSD5",
        x: 300,
        y: 360,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "shipping",
        color: COLOR_TODO,
      },
      {
        id: "sd6",
        labelKey: "nodeSD6",
        x: 80,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "billing",
        color: COLOR_PENDING,
      },
      {
        id: "sd7",
        labelKey: "nodeSD7",
        x: 520,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "introSD",
        color: COLOR_PENDING,
      },
      {
        id: "sd8",
        labelKey: "nodeSD8",
        x: 300,
        y: 560,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "shipping",
        color: COLOR_PENDING,
      },
      {
        id: "sd9",
        labelKey: "nodeSD9",
        x: 300,
        y: 660,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "billing",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "sd1", to: "sd2" },
      { from: "sd2", to: "sd3" },
      { from: "sd2", to: "sd4" },
      { from: "sd3", to: "sd5" },
      { from: "sd5", to: "sd6" },
      { from: "sd5", to: "sd7" },
      { from: "sd6", to: "sd8" },
      { from: "sd7", to: "sd8" },
      { from: "sd8", to: "sd9" },
    ],
  },
  // SAP FI Key User
  {
    id: "sap-fi",
    titleKey: "cardSapFI",
    descKey: "descSapFI",
    nodes: [
      {
        id: "fi1",
        labelKey: "nodeFI1",
        x: 300,
        y: 60,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "introFI",
        color: COLOR_DONE,
      },
      {
        id: "fi2",
        labelKey: "nodeFI2",
        x: 300,
        y: 160,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "introFI",
        color: COLOR_DONE,
      },
      {
        id: "fi3",
        labelKey: "nodeFI3",
        x: 80,
        y: 260,
        width: 240,
        height: 52,
        status: "in-progress",
        detailKey: "gl",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "fi4",
        labelKey: "nodeFI4",
        x: 520,
        y: 260,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "ap",
        color: COLOR_TODO,
      },
      {
        id: "fi5",
        labelKey: "nodeFI5",
        x: 300,
        y: 360,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "ar",
        color: COLOR_TODO,
      },
      {
        id: "fi6",
        labelKey: "nodeFI6",
        x: 300,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "asset",
        color: COLOR_PENDING,
      },
      {
        id: "fi7",
        labelKey: "nodeFI7",
        x: 300,
        y: 560,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "reporting",
        color: COLOR_PENDING,
      },
      {
        id: "fi8",
        labelKey: "nodeFI8",
        x: 300,
        y: 660,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "reporting",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "fi1", to: "fi2" },
      { from: "fi2", to: "fi3" },
      { from: "fi2", to: "fi4" },
      { from: "fi3", to: "fi5" },
      { from: "fi4", to: "fi5" },
      { from: "fi5", to: "fi6" },
      { from: "fi6", to: "fi7" },
      { from: "fi7", to: "fi8" },
    ],
  },
  // SAP MM Consultant
  {
    id: "sap-consultant-mm",
    titleKey: "cardSapConsultantMM",
    descKey: "descSapConsultantMM",
    nodes: [
      {
        id: "cmm1",
        labelKey: "nodeCMM1",
        x: 300,
        y: 60,
        width: 260,
        height: 52,
        status: "done",
        detailKey: "configMM",
        color: COLOR_DONE,
      },
      {
        id: "cmm2",
        labelKey: "nodeCMM2",
        x: 300,
        y: 160,
        width: 260,
        height: 52,
        status: "done",
        detailKey: "configMM",
        color: COLOR_DONE,
      },
      {
        id: "cmm3",
        labelKey: "nodeCMM3",
        x: 80,
        y: 260,
        width: 260,
        height: 52,
        status: "in-progress",
        detailKey: "purchasing",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "cmm4",
        labelKey: "nodeCMM4",
        x: 520,
        y: 260,
        width: 260,
        height: 52,
        status: "todo",
        detailKey: "inventory",
        color: COLOR_TODO,
      },
      {
        id: "cmm5",
        labelKey: "nodeCMM5",
        x: 300,
        y: 360,
        width: 260,
        height: 52,
        status: "todo",
        detailKey: "invoice",
        color: COLOR_TODO,
      },
      {
        id: "cmm6",
        labelKey: "nodeCMM6",
        x: 80,
        y: 460,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "configMM",
        color: COLOR_PENDING,
      },
      {
        id: "cmm7",
        labelKey: "nodeCMM7",
        x: 520,
        y: 460,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "configMM",
        color: COLOR_PENDING,
      },
      {
        id: "cmm8",
        labelKey: "nodeCMM8",
        x: 300,
        y: 560,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "configMM",
        color: COLOR_PENDING,
      },
      {
        id: "cmm9",
        labelKey: "nodeCMM9",
        x: 300,
        y: 660,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "configMM",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "cmm1", to: "cmm2" },
      { from: "cmm2", to: "cmm3" },
      { from: "cmm2", to: "cmm4" },
      { from: "cmm3", to: "cmm5" },
      { from: "cmm4", to: "cmm5" },
      { from: "cmm5", to: "cmm6" },
      { from: "cmm5", to: "cmm7" },
      { from: "cmm6", to: "cmm8" },
      { from: "cmm7", to: "cmm8" },
      { from: "cmm8", to: "cmm9" },
    ],
  },
  // SAP SD Consultant
  {
    id: "sap-consultant-sd",
    titleKey: "cardSapConsultantSD",
    descKey: "descSapConsultantSD",
    nodes: [
      {
        id: "csd1",
        labelKey: "nodeCSD1",
        x: 300,
        y: 60,
        width: 260,
        height: 52,
        status: "done",
        detailKey: "configSD",
        color: COLOR_DONE,
      },
      {
        id: "csd2",
        labelKey: "nodeCSD2",
        x: 300,
        y: 160,
        width: 260,
        height: 52,
        status: "done",
        detailKey: "configSD",
        color: COLOR_DONE,
      },
      {
        id: "csd3",
        labelKey: "nodeCSD3",
        x: 80,
        y: 260,
        width: 260,
        height: 52,
        status: "in-progress",
        detailKey: "salesDoc",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "csd4",
        labelKey: "nodeCSD4",
        x: 520,
        y: 260,
        width: 260,
        height: 52,
        status: "todo",
        detailKey: "pricingSD",
        color: COLOR_TODO,
      },
      {
        id: "csd5",
        labelKey: "nodeCSD5",
        x: 300,
        y: 360,
        width: 260,
        height: 52,
        status: "todo",
        detailKey: "shippingSD",
        color: COLOR_TODO,
      },
      {
        id: "csd6",
        labelKey: "nodeCSD6",
        x: 80,
        y: 460,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "billingSD",
        color: COLOR_PENDING,
      },
      {
        id: "csd7",
        labelKey: "nodeCSD7",
        x: 520,
        y: 460,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "configSD",
        color: COLOR_PENDING,
      },
      {
        id: "csd8",
        labelKey: "nodeCSD8",
        x: 300,
        y: 560,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "configSD",
        color: COLOR_PENDING,
      },
      {
        id: "csd9",
        labelKey: "nodeCSD9",
        x: 300,
        y: 660,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "configSD",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "csd1", to: "csd2" },
      { from: "csd2", to: "csd3" },
      { from: "csd2", to: "csd4" },
      { from: "csd3", to: "csd5" },
      { from: "csd4", to: "csd5" },
      { from: "csd5", to: "csd6" },
      { from: "csd5", to: "csd7" },
      { from: "csd6", to: "csd8" },
      { from: "csd7", to: "csd8" },
      { from: "csd8", to: "csd9" },
    ],
  },
  // SAP FI Consultant
  {
    id: "sap-consultant-fi",
    titleKey: "cardSapConsultantFI",
    descKey: "descSapConsultantFI",
    nodes: [
      {
        id: "cfi1",
        labelKey: "nodeCFI1",
        x: 300,
        y: 60,
        width: 260,
        height: 52,
        status: "done",
        detailKey: "configFI",
        color: COLOR_DONE,
      },
      {
        id: "cfi2",
        labelKey: "nodeCFI2",
        x: 300,
        y: 160,
        width: 260,
        height: 52,
        status: "done",
        detailKey: "configFI",
        color: COLOR_DONE,
      },
      {
        id: "cfi3",
        labelKey: "nodeCFI3",
        x: 80,
        y: 260,
        width: 260,
        height: 52,
        status: "in-progress",
        detailKey: "glConfig",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "cfi4",
        labelKey: "nodeCFI4",
        x: 520,
        y: 260,
        width: 260,
        height: 52,
        status: "todo",
        detailKey: "arConfig",
        color: COLOR_TODO,
      },
      {
        id: "cfi5",
        labelKey: "nodeCFI5",
        x: 300,
        y: 360,
        width: 260,
        height: 52,
        status: "todo",
        detailKey: "apConfig",
        color: COLOR_TODO,
      },
      {
        id: "cfi6",
        labelKey: "nodeCFI6",
        x: 80,
        y: 460,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "assetConfig",
        color: COLOR_PENDING,
      },
      {
        id: "cfi7",
        labelKey: "nodeCFI7",
        x: 520,
        y: 460,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "bankConfig",
        color: COLOR_PENDING,
      },
      {
        id: "cfi8",
        labelKey: "nodeCFI8",
        x: 300,
        y: 560,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "configFI",
        color: COLOR_PENDING,
      },
      {
        id: "cfi9",
        labelKey: "nodeCFI9",
        x: 300,
        y: 660,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "configFI",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "cfi1", to: "cfi2" },
      { from: "cfi2", to: "cfi3" },
      { from: "cfi2", to: "cfi4" },
      { from: "cfi3", to: "cfi5" },
      { from: "cfi4", to: "cfi5" },
      { from: "cfi5", to: "cfi6" },
      { from: "cfi5", to: "cfi7" },
      { from: "cfi6", to: "cfi8" },
      { from: "cfi7", to: "cfi8" },
      { from: "cfi8", to: "cfi9" },
    ],
  },
  // Power Automate
  {
    id: "power-automate",
    titleKey: "cardPowerAutomate",
    descKey: "descPowerAutomate",
    nodes: [
      {
        id: "pau1",
        labelKey: "nodePAU1",
        x: 300,
        y: 60,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "flowBasics",
        color: COLOR_DONE,
      },
      {
        id: "pau2",
        labelKey: "nodePAU2",
        x: 300,
        y: 160,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "flowBasics",
        color: COLOR_DONE,
      },
      {
        id: "pau3",
        labelKey: "nodePAU3",
        x: 80,
        y: 260,
        width: 240,
        height: 52,
        status: "in-progress",
        detailKey: "automated",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "pau4",
        labelKey: "nodePAU4",
        x: 520,
        y: 260,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "instant",
        color: COLOR_TODO,
      },
      {
        id: "pau5",
        labelKey: "nodePAU5",
        x: 300,
        y: 360,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "scheduled",
        color: COLOR_TODO,
      },
      {
        id: "pau6",
        labelKey: "nodePAU6",
        x: 80,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "rpa",
        color: COLOR_PENDING,
      },
      {
        id: "pau7",
        labelKey: "nodePAU7",
        x: 520,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "connectors",
        color: COLOR_PENDING,
      },
      {
        id: "pau8",
        labelKey: "nodePAU8",
        x: 300,
        y: 560,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "connectors",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "pau1", to: "pau2" },
      { from: "pau2", to: "pau3" },
      { from: "pau2", to: "pau4" },
      { from: "pau2", to: "pau5" },
      { from: "pau3", to: "pau6" },
      { from: "pau4", to: "pau7" },
      { from: "pau5", to: "pau6" },
      { from: "pau5", to: "pau7" },
      { from: "pau6", to: "pau8" },
      { from: "pau7", to: "pau8" },
    ],
  },
  // Power BI
  {
    id: "power-bi",
    titleKey: "cardPowerBI",
    descKey: "descPowerBI",
    nodes: [
      {
        id: "pbi1",
        labelKey: "nodePBI1",
        x: 300,
        y: 60,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "pbiIntro",
        color: COLOR_DONE,
      },
      {
        id: "pbi2",
        labelKey: "nodePBI2",
        x: 300,
        y: 160,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "pbiData",
        color: COLOR_DONE,
      },
      {
        id: "pbi3",
        labelKey: "nodePBI3",
        x: 80,
        y: 260,
        width: 240,
        height: 52,
        status: "in-progress",
        detailKey: "pbiModel",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "pbi4",
        labelKey: "nodePBI4",
        x: 520,
        y: 260,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "pbi Dax",
        color: COLOR_TODO,
      },
      {
        id: "pbi5",
        labelKey: "nodePBI5",
        x: 300,
        y: 360,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "pbiViz",
        color: COLOR_TODO,
      },
      {
        id: "pbi6",
        labelKey: "nodePBI6",
        x: 80,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "pbiService",
        color: COLOR_PENDING,
      },
      {
        id: "pbi7",
        labelKey: "nodePBI7",
        x: 520,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "pbiSecurity",
        color: COLOR_PENDING,
      },
      {
        id: "pbi8",
        labelKey: "nodePBI8",
        x: 300,
        y: 560,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "pbiService",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "pbi1", to: "pbi2" },
      { from: "pbi2", to: "pbi3" },
      { from: "pbi2", to: "pbi4" },
      { from: "pbi3", to: "pbi5" },
      { from: "pbi4", to: "pbi5" },
      { from: "pbi5", to: "pbi6" },
      { from: "pbi5", to: "pbi7" },
      { from: "pbi6", to: "pbi8" },
      { from: "pbi7", to: "pbi8" },
    ],
  },
  // Jira
  {
    id: "jira",
    titleKey: "cardJira",
    descKey: "descJira",
    nodes: [
      {
        id: "jira1",
        labelKey: "nodeJira1",
        x: 300,
        y: 60,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "jiraIntro",
        color: COLOR_DONE,
      },
      {
        id: "jira2",
        labelKey: "nodeJira2",
        x: 300,
        y: 160,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "jiraProjects",
        color: COLOR_DONE,
      },
      {
        id: "jira3",
        labelKey: "nodeJira3",
        x: 80,
        y: 260,
        width: 240,
        height: 52,
        status: "in-progress",
        detailKey: "jiraAgile",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "jira4",
        labelKey: "nodeJira4",
        x: 520,
        y: 260,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "jiraWorkflow",
        color: COLOR_TODO,
      },
      {
        id: "jira5",
        labelKey: "nodeJira5",
        x: 300,
        y: 360,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "jiraScrum",
        color: COLOR_TODO,
      },
      {
        id: "jira6",
        labelKey: "nodeJira6",
        x: 80,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "jiraKanban",
        color: COLOR_PENDING,
      },
      {
        id: "jira7",
        labelKey: "nodeJira7",
        x: 520,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "jiraReports",
        color: COLOR_PENDING,
      },
      {
        id: "jira8",
        labelKey: "nodeJira8",
        x: 300,
        y: 560,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "jiraReports",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "jira1", to: "jira2" },
      { from: "jira2", to: "jira3" },
      { from: "jira2", to: "jira4" },
      { from: "jira3", to: "jira5" },
      { from: "jira4", to: "jira5" },
      { from: "jira5", to: "jira6" },
      { from: "jira5", to: "jira7" },
      { from: "jira6", to: "jira8" },
      { from: "jira7", to: "jira8" },
    ],
  },
  // ServiceNow
  {
    id: "servicenow",
    titleKey: "cardServiceNow",
    descKey: "descServiceNow",
    nodes: [
      {
        id: "sn1",
        labelKey: "nodeSN1",
        x: 300,
        y: 60,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "snIntro",
        color: COLOR_DONE,
      },
      {
        id: "sn2",
        labelKey: "nodeSN2",
        x: 300,
        y: 160,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "snItsm",
        color: COLOR_DONE,
      },
      {
        id: "sn3",
        labelKey: "nodeSN3",
        x: 80,
        y: 260,
        width: 240,
        height: 52,
        status: "in-progress",
        detailKey: "snIncident",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "sn4",
        labelKey: "nodeSN4",
        x: 520,
        y: 260,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "snProblem",
        color: COLOR_TODO,
      },
      {
        id: "sn5",
        labelKey: "nodeSN5",
        x: 300,
        y: 360,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "snChange",
        color: COLOR_TODO,
      },
      {
        id: "sn6",
        labelKey: "nodeSN6",
        x: 80,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "snAsset",
        color: COLOR_PENDING,
      },
      {
        id: "sn7",
        labelKey: "nodeSN7",
        x: 520,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "snCatalog",
        color: COLOR_PENDING,
      },
      {
        id: "sn8",
        labelKey: "nodeSN8",
        x: 300,
        y: 560,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "snCatalog",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "sn1", to: "sn2" },
      { from: "sn2", to: "sn3" },
      { from: "sn2", to: "sn4" },
      { from: "sn3", to: "sn5" },
      { from: "sn4", to: "sn5" },
      { from: "sn5", to: "sn6" },
      { from: "sn5", to: "sn7" },
      { from: "sn6", to: "sn8" },
      { from: "sn7", to: "sn8" },
    ],
  },
  // SharePoint Workflows
  {
    id: "sharepoint",
    titleKey: "cardSharePoint",
    descKey: "descSharePoint",
    nodes: [
      {
        id: "sp1",
        labelKey: "nodeSP1",
        x: 300,
        y: 60,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "spIntro",
        color: COLOR_DONE,
      },
      {
        id: "sp2",
        labelKey: "nodeSP2",
        x: 300,
        y: 160,
        width: 240,
        height: 52,
        status: "done",
        detailKey: "spLists",
        color: COLOR_DONE,
      },
      {
        id: "sp3",
        labelKey: "nodeSP3",
        x: 80,
        y: 260,
        width: 240,
        height: 52,
        status: "in-progress",
        detailKey: "spPowerAutomate",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "sp4",
        labelKey: "nodeSP4",
        x: 520,
        y: 260,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "spApproval",
        color: COLOR_TODO,
      },
      {
        id: "sp5",
        labelKey: "nodeSP5",
        x: 300,
        y: 360,
        width: 240,
        height: 52,
        status: "todo",
        detailKey: "spIntegration",
        color: COLOR_TODO,
      },
      {
        id: "sp6",
        labelKey: "nodeSP6",
        x: 80,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "spAutomation",
        color: COLOR_PENDING,
      },
      {
        id: "sp7",
        labelKey: "nodeSP7",
        x: 520,
        y: 460,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "spGovernance",
        color: COLOR_PENDING,
      },
      {
        id: "sp8",
        labelKey: "nodeSP8",
        x: 300,
        y: 560,
        width: 240,
        height: 52,
        status: "pending",
        detailKey: "spGovernance",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "sp1", to: "sp2" },
      { from: "sp2", to: "sp3" },
      { from: "sp2", to: "sp4" },
      { from: "sp3", to: "sp5" },
      { from: "sp4", to: "sp5" },
      { from: "sp5", to: "sp6" },
      { from: "sp5", to: "sp7" },
      { from: "sp6", to: "sp8" },
      { from: "sp7", to: "sp8" },
    ],
  },
  // Foundations across all journeys
  {
    id: "journey-foundations",
    titleKey: "cardJourneyFoundations",
    descKey: "descJourneyFoundations",
    nodes: [
      {
        id: "jf1",
        labelKey: "nodeJF1",
        x: 300,
        y: 60,
        width: 260,
        height: 52,
        status: "done",
        detailKey: "introMM",
        color: COLOR_DONE,
      },
      {
        id: "jf2",
        labelKey: "nodeJF2",
        x: 300,
        y: 160,
        width: 260,
        height: 52,
        status: "done",
        detailKey: "introSD",
        color: COLOR_DONE,
      },
      {
        id: "jf3",
        labelKey: "nodeJF3",
        x: 80,
        y: 260,
        width: 260,
        height: 52,
        status: "in-progress",
        detailKey: "introFI",
        color: COLOR_IN_PROGRESS,
      },
      {
        id: "jf4",
        labelKey: "nodeJF4",
        x: 520,
        y: 260,
        width: 260,
        height: 52,
        status: "todo",
        detailKey: "canvas",
        color: COLOR_TODO,
      },
      {
        id: "jf5",
        labelKey: "nodeJF5",
        x: 300,
        y: 360,
        width: 260,
        height: 52,
        status: "todo",
        detailKey: "flowBasics",
        color: COLOR_TODO,
      },
      {
        id: "jf6",
        labelKey: "nodeJF6",
        x: 80,
        y: 460,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "pbiIntro",
        color: COLOR_PENDING,
      },
      {
        id: "jf7",
        labelKey: "nodeJF7",
        x: 520,
        y: 460,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "jiraIntro",
        color: COLOR_PENDING,
      },
      {
        id: "jf8",
        labelKey: "nodeJF8",
        x: 300,
        y: 560,
        width: 260,
        height: 52,
        status: "pending",
        detailKey: "snIntro",
        color: COLOR_PENDING,
      },
    ],
    edges: [
      { from: "jf1", to: "jf2" },
      { from: "jf2", to: "jf3" },
      { from: "jf2", to: "jf4" },
      { from: "jf3", to: "jf5" },
      { from: "jf4", to: "jf5" },
      { from: "jf5", to: "jf6" },
      { from: "jf5", to: "jf7" },
      { from: "jf6", to: "jf8" },
      { from: "jf7", to: "jf8" },
    ],
  },
]

export interface NodeDetail {
  titleKey: keyof (typeof translations)["en"]
  theoryKey: keyof (typeof translations)["en"]
  technicalKey: keyof (typeof translations)["en"]
  checklistKey: keyof (typeof translations)["en"]
}

// O Mapeamento dos Detalhes que abrem na gaveta (Sheet/Modal)
export const nodeDetails: Record<string, NodeDetail> = {
  p2p: {
    titleKey: "detailP2PTitle",
    theoryKey: "detailP2PTheory",
    technicalKey: "detailP2PTechnical",
    checklistKey: "detailP2PChecklist",
  },
  introMM: {
    titleKey: "detailIntroMMTitle",
    theoryKey: "detailIntroMMTheory",
    technicalKey: "detailIntroMMTechnical",
    checklistKey: "detailIntroMMChecklist",
  },
  mmOrgStructure: {
    titleKey: "detailMMOrgStructureTitle",
    theoryKey: "detailMMOrgStructureTheory",
    technicalKey: "detailMMOrgStructureTechnical",
    checklistKey: "detailMMOrgStructureChecklist",
  },
  mmMasterData: {
    titleKey: "detailMMMasterDataTitle",
    theoryKey: "detailMMMasterDataTheory",
    technicalKey: "detailMMMasterDataTechnical",
    checklistKey: "detailMMMasterDataChecklist",
  },
  mmPurchasingMaster: {
    titleKey: "detailMMPurchasingMasterTitle",
    theoryKey: "detailMMPurchasingMasterTheory",
    technicalKey: "detailMMPurchasingMasterTechnical",
    checklistKey: "detailMMPurchasingMasterChecklist",
  },
  mmPurchaseReq: {
    titleKey: "detailMMPurchaseReqTitle",
    theoryKey: "detailMMPurchaseReqTheory",
    technicalKey: "detailMMPurchaseReqTechnical",
    checklistKey: "detailMMPurchaseReqChecklist",
  },
  mmPurchaseOrder: {
    titleKey: "detailMMPurchaseOrderTitle",
    theoryKey: "detailMMPurchaseOrderTheory",
    technicalKey: "detailMMPurchaseOrderTechnical",
    checklistKey: "detailMMPurchaseOrderChecklist",
  },
  mmReleaseStrategy: {
    titleKey: "detailMMReleaseStrategyTitle",
    theoryKey: "detailMMReleaseStrategyTheory",
    technicalKey: "detailMMReleaseStrategyTechnical",
    checklistKey: "detailMMReleaseStrategyChecklist",
  },
  mmInventoryMigo: {
    titleKey: "detailMMInventoryMigoTitle",
    theoryKey: "detailMMInventoryMigoTheory",
    technicalKey: "detailMMInventoryMigoTechnical",
    checklistKey: "detailMMInventoryMigoChecklist",
  },
  mmInvoiceMiro: {
    titleKey: "detailMMInvoiceMiroTitle",
    theoryKey: "detailMMInvoiceMiroTheory",
    technicalKey: "detailMMInvoiceMiroTechnical",
    checklistKey: "detailMMInvoiceMiroChecklist",
  },
  mmOutlineAgreements: {
    titleKey: "detailMMOutlineAgreementsTitle",
    theoryKey: "detailMMOutlineAgreementsTheory",
    technicalKey: "detailMMOutlineAgreementsTechnical",
    checklistKey: "detailMMOutlineAgreementsChecklist",
  },
  mmSubcontractingConsignment: {
    titleKey: "detailMMSubcontractingConsignmentTitle",
    theoryKey: "detailMMSubcontractingConsignmentTheory",
    technicalKey: "detailMMSubcontractingConsignmentTechnical",
    checklistKey: "detailMMSubcontractingConsignmentChecklist",
  },
  mmMrp: {
    titleKey: "detailMMMrpTitle",
    theoryKey: "detailMMMrpTheory",
    technicalKey: "detailMMMrpTechnical",
    checklistKey: "detailMMMrpChecklist",
  },
  mmDataAutomation: {
    titleKey: "detailMMDataAutomationTitle",
    theoryKey: "detailMMDataAutomationTheory",
    technicalKey: "detailMMDataAutomationTechnical",
    checklistKey: "detailMMDataAutomationChecklist",
  },
  canvas: {
    titleKey: "detailCanvasTitle",
    theoryKey: "detailCanvasTheory",
    technicalKey: "detailCanvasTechnical",
    checklistKey: "detailCanvasChecklist",
  },
  schema: {
    titleKey: "detailSchemaTitle",
    theoryKey: "detailSchemaTheory",
    technicalKey: "detailSchemaTechnical",
    checklistKey: "detailSchemaChecklist",
  },
  // SAP SD
  introSD: {
    titleKey: "detailIntroSDTitle",
    theoryKey: "detailIntroSDTheory",
    technicalKey: "detailIntroSDTechnical",
    checklistKey: "detailIntroSDChecklist",
  },
  sales: {
    titleKey: "detailSalesTitle",
    theoryKey: "detailSalesTheory",
    technicalKey: "detailSalesTechnical",
    checklistKey: "detailSalesChecklist",
  },
  pricing: {
    titleKey: "detailPricingTitle",
    theoryKey: "detailPricingTheory",
    technicalKey: "detailPricingTechnical",
    checklistKey: "detailPricingChecklist",
  },
  shipping: {
    titleKey: "detailShippingTitle",
    theoryKey: "detailShippingTheory",
    technicalKey: "detailShippingTechnical",
    checklistKey: "detailShippingChecklist",
  },
  billing: {
    titleKey: "detailBillingTitle",
    theoryKey: "detailBillingTheory",
    technicalKey: "detailBillingTechnical",
    checklistKey: "detailBillingChecklist",
  },
  // SAP FI
  introFI: {
    titleKey: "detailIntroFITitle",
    theoryKey: "detailIntroFITheory",
    technicalKey: "detailIntroFITechnical",
    checklistKey: "detailIntroFIChecklist",
  },
  gl: {
    titleKey: "detailGLTitle",
    theoryKey: "detailGLTheory",
    technicalKey: "detailGLTechnical",
    checklistKey: "detailGLChecklist",
  },
  ap: {
    titleKey: "detailAPTitle",
    theoryKey: "detailAPTheory",
    technicalKey: "detailAPTechnical",
    checklistKey: "detailAPChecklist",
  },
  ar: {
    titleKey: "detailARTitle",
    theoryKey: "detailARTheory",
    technicalKey: "detailARTechnical",
    checklistKey: "detailARChecklist",
  },
  asset: {
    titleKey: "detailAssetTitle",
    theoryKey: "detailAssetTheory",
    technicalKey: "detailAssetTechnical",
    checklistKey: "detailAssetChecklist",
  },
  reporting: {
    titleKey: "detailReportingTitle",
    theoryKey: "detailReportingTheory",
    technicalKey: "detailReportingTechnical",
    checklistKey: "detailReportingChecklist",
  },
  // SAP MM Consultant
  configMM: {
    titleKey: "detailConfigMMTitle",
    theoryKey: "detailConfigMMTheory",
    technicalKey: "detailConfigMMTechnical",
    checklistKey: "detailConfigMMChecklist",
  },
  purchasing: {
    titleKey: "detailPurchasingTitle",
    theoryKey: "detailPurchasingTheory",
    technicalKey: "detailPurchasingTechnical",
    checklistKey: "detailPurchasingChecklist",
  },
  inventory: {
    titleKey: "detailInventoryTitle",
    theoryKey: "detailInventoryTheory",
    technicalKey: "detailInventoryTechnical",
    checklistKey: "detailInventoryChecklist",
  },
  invoice: {
    titleKey: "detailInvoiceTitle",
    theoryKey: "detailInvoiceTheory",
    technicalKey: "detailInvoiceTechnical",
    checklistKey: "detailInvoiceChecklist",
  },
  // SAP SD Consultant
  configSD: {
    titleKey: "detailConfigSDTitle",
    theoryKey: "detailConfigSDTheory",
    technicalKey: "detailConfigSDTechnical",
    checklistKey: "detailConfigSDChecklist",
  },
  salesDoc: {
    titleKey: "detailSalesDocTitle",
    theoryKey: "detailSalesDocTheory",
    technicalKey: "detailSalesDocTechnical",
    checklistKey: "detailSalesDocChecklist",
  },
  pricingSD: {
    titleKey: "detailPricingSDTitle",
    theoryKey: "detailPricingSDTheory",
    technicalKey: "detailPricingSDTechnical",
    checklistKey: "detailPricingSDChecklist",
  },
  shippingSD: {
    titleKey: "detailShippingSDTitle",
    theoryKey: "detailShippingSDTheory",
    technicalKey: "detailShippingSDTechnical",
    checklistKey: "detailShippingSDChecklist",
  },
  billingSD: {
    titleKey: "detailBillingSDTitle",
    theoryKey: "detailBillingSDTheory",
    technicalKey: "detailBillingSDTechnical",
    checklistKey: "detailBillingSDChecklist",
  },
  // SAP FI Consultant
  configFI: {
    titleKey: "detailConfigFITitle",
    theoryKey: "detailConfigFITheory",
    technicalKey: "detailConfigFITechnical",
    checklistKey: "detailConfigFIChecklist",
  },
  glConfig: {
    titleKey: "detailGLConfigTitle",
    theoryKey: "detailGLConfigTheory",
    technicalKey: "detailGLConfigTechnical",
    checklistKey: "detailGLConfigChecklist",
  },
  arConfig: {
    titleKey: "detailARConfigTitle",
    theoryKey: "detailARConfigTheory",
    technicalKey: "detailARConfigTechnical",
    checklistKey: "detailARConfigChecklist",
  },
  apConfig: {
    titleKey: "detailAPConfigTitle",
    theoryKey: "detailAPConfigTheory",
    technicalKey: "detailAPConfigTechnical",
    checklistKey: "detailAPConfigChecklist",
  },
  assetConfig: {
    titleKey: "detailAssetConfigTitle",
    theoryKey: "detailAssetConfigTheory",
    technicalKey: "detailAssetConfigTechnical",
    checklistKey: "detailAssetConfigChecklist",
  },
  bankConfig: {
    titleKey: "detailBankConfigTitle",
    theoryKey: "detailBankConfigTheory",
    technicalKey: "detailBankConfigTechnical",
    checklistKey: "detailBankConfigChecklist",
  },
  // Power Automate
  flowBasics: {
    titleKey: "detailFlowBasicsTitle",
    theoryKey: "detailFlowBasicsTheory",
    technicalKey: "detailFlowBasicsTechnical",
    checklistKey: "detailFlowBasicsChecklist",
  },
  automated: {
    titleKey: "detailAutomatedTitle",
    theoryKey: "detailAutomatedTheory",
    technicalKey: "detailAutomatedTechnical",
    checklistKey: "detailAutomatedChecklist",
  },
  instant: {
    titleKey: "detailInstantTitle",
    theoryKey: "detailInstantTheory",
    technicalKey: "detailInstantTechnical",
    checklistKey: "detailInstantChecklist",
  },
  scheduled: {
    titleKey: "detailScheduledTitle",
    theoryKey: "detailScheduledTheory",
    technicalKey: "detailScheduledTechnical",
    checklistKey: "detailScheduledChecklist",
  },
  rpa: {
    titleKey: "detailRPATitle",
    theoryKey: "detailRPATheory",
    technicalKey: "detailRPATechnical",
    checklistKey: "detailRPAChecklist",
  },
  connectors: {
    titleKey: "detailConnectorsTitle",
    theoryKey: "detailConnectorsTheory",
    technicalKey: "detailConnectorsTechnical",
    checklistKey: "detailConnectorsChecklist",
  },
  // Power BI
  pbiIntro: {
    titleKey: "detailPBIIntroTitle",
    theoryKey: "detailPBIIntroTheory",
    technicalKey: "detailPBIIntroTechnical",
    checklistKey: "detailPBIIntroChecklist",
  },
  pbiData: {
    titleKey: "detailPBIDataTitle",
    theoryKey: "detailPBIDataTheory",
    technicalKey: "detailPBIDataTechnical",
    checklistKey: "detailPBIDataChecklist",
  },
  pbiModel: {
    titleKey: "detailPBIModelTitle",
    theoryKey: "detailPBIModelTheory",
    technicalKey: "detailPBIModelTechnical",
    checklistKey: "detailPBIModelChecklist",
  },
  pbiDax: {
    titleKey: "detailPBIDaxTitle",
    theoryKey: "detailPBIDaxTheory",
    technicalKey: "detailPBIDaxTechnical",
    checklistKey: "detailPBIDaxChecklist",
  },
  pbiViz: {
    titleKey: "detailPBIVizTitle",
    theoryKey: "detailPBIVizTheory",
    technicalKey: "detailPBIVizTechnical",
    checklistKey: "detailPBIVizChecklist",
  },
  pbiService: {
    titleKey: "detailPBIServiceTitle",
    theoryKey: "detailPBIServiceTheory",
    technicalKey: "detailPBIServiceTechnical",
    checklistKey: "detailPBIServiceChecklist",
  },
  pbiSecurity: {
    titleKey: "detailPBISecurityTitle",
    theoryKey: "detailPBISecurityTheory",
    technicalKey: "detailPBISecurityTechnical",
    checklistKey: "detailPBISecurityChecklist",
  },
  // Jira
  jiraIntro: {
    titleKey: "detailJiraIntroTitle",
    theoryKey: "detailJiraIntroTheory",
    technicalKey: "detailJiraIntroTechnical",
    checklistKey: "detailJiraIntroChecklist",
  },
  jiraProjects: {
    titleKey: "detailJiraProjectsTitle",
    theoryKey: "detailJiraProjectsTheory",
    technicalKey: "detailJiraProjectsTechnical",
    checklistKey: "detailJiraProjectsChecklist",
  },
  jiraAgile: {
    titleKey: "detailJiraAgileTitle",
    theoryKey: "detailJiraAgileTheory",
    technicalKey: "detailJiraAgileTechnical",
    checklistKey: "detailJiraAgileChecklist",
  },
  jiraWorkflow: {
    titleKey: "detailJiraWorkflowTitle",
    theoryKey: "detailJiraWorkflowTheory",
    technicalKey: "detailJiraWorkflowTechnical",
    checklistKey: "detailJiraWorkflowChecklist",
  },
  jiraScrum: {
    titleKey: "detailJiraScrumTitle",
    theoryKey: "detailJiraScrumTheory",
    technicalKey: "detailJiraScrumTechnical",
    checklistKey: "detailJiraScrumChecklist",
  },
  jiraKanban: {
    titleKey: "detailJiraKanbanTitle",
    theoryKey: "detailJiraKanbanTheory",
    technicalKey: "detailJiraKanbanTechnical",
    checklistKey: "detailJiraKanbanChecklist",
  },
  jiraReports: {
    titleKey: "detailJiraReportsTitle",
    theoryKey: "detailJiraReportsTheory",
    technicalKey: "detailJiraReportsTechnical",
    checklistKey: "detailJiraReportsChecklist",
  },
  // ServiceNow
  snIntro: {
    titleKey: "detailSNIntroTitle",
    theoryKey: "detailSNIntroTheory",
    technicalKey: "detailSNIntroTechnical",
    checklistKey: "detailSNIntroChecklist",
  },
  snItsm: {
    titleKey: "detailSNITSMTitle",
    theoryKey: "detailSNITSMTheory",
    technicalKey: "detailSNITSMTechnical",
    checklistKey: "detailSNITSMChecklist",
  },
  snIncident: {
    titleKey: "detailSNIncidentTitle",
    theoryKey: "detailSNIncidentTheory",
    technicalKey: "detailSNIncidentTechnical",
    checklistKey: "detailSNIncidentChecklist",
  },
  snProblem: {
    titleKey: "detailSNProblemTitle",
    theoryKey: "detailSNProblemTheory",
    technicalKey: "detailSNProblemTechnical",
    checklistKey: "detailSNProblemChecklist",
  },
  snChange: {
    titleKey: "detailSNChangeTitle",
    theoryKey: "detailSNChangeTheory",
    technicalKey: "detailSNChangeTechnical",
    checklistKey: "detailSNChangeChecklist",
  },
  snAsset: {
    titleKey: "detailSNAssetTitle",
    theoryKey: "detailSNAssetTheory",
    technicalKey: "detailSNAssetTechnical",
    checklistKey: "detailSNAssetChecklist",
  },
  snCatalog: {
    titleKey: "detailSNCatalogTitle",
    theoryKey: "detailSNCatalogTheory",
    technicalKey: "detailSNCatalogTechnical",
    checklistKey: "detailSNCatalogChecklist",
  },
  // SharePoint
  spIntro: {
    titleKey: "detailSPIntroTitle",
    theoryKey: "detailSPIntroTheory",
    technicalKey: "detailSPIntroTechnical",
    checklistKey: "detailSPIntroChecklist",
  },
  spLists: {
    titleKey: "detailSPListsTitle",
    theoryKey: "detailSPListsTheory",
    technicalKey: "detailSPListsTechnical",
    checklistKey: "detailSPListsChecklist",
  },
  spPowerAutomate: {
    titleKey: "detailSPPowerAutomateTitle",
    theoryKey: "detailSPPowerAutomateTheory",
    technicalKey: "detailSPPowerAutomateTechnical",
    checklistKey: "detailSPPowerAutomateChecklist",
  },
  spApproval: {
    titleKey: "detailSPApprovalTitle",
    theoryKey: "detailSPApprovalTheory",
    technicalKey: "detailSPApprovalTechnical",
    checklistKey: "detailSPApprovalChecklist",
  },
  spIntegration: {
    titleKey: "detailSPIntegrationTitle",
    theoryKey: "detailSPIntegrationTheory",
    technicalKey: "detailSPIntegrationTechnical",
    checklistKey: "detailSPIntegrationChecklist",
  },
  spAutomation: {
    titleKey: "detailSPAutomationTitle",
    theoryKey: "detailSPAutomationTheory",
    technicalKey: "detailSPAutomationTechnical",
    checklistKey: "detailSPAutomationChecklist",
  },
  spGovernance: {
    titleKey: "detailSPGovernanceTitle",
    theoryKey: "detailSPGovernanceTheory",
    technicalKey: "detailSPGovernanceTechnical",
    checklistKey: "detailSPGovernanceChecklist",
  },
}

export function getRoadmapById(id: string): RoadmapData | undefined {
  return roadmaps.find((r) => r.id === id)
}

export function getNodeLabel(node: RoadmapNode, lang: Lang): string {
  return translations[lang][node.labelKey] as string
}
